#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Tecvity
email: hello@tecvity.co
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Team names, titles and social links
people:
  - name: Najam Ul Saqib
    pic: najam
    position: Chief Executive Officer (CEO)
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: stack-overflow
    #     url: #

  - name: Moeez Ahmed
    position: Chief Technological Officer (CTO)
    pic: 2
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: linkedin
    #     url: #

  - name: Tayyab Ahmed
    pic: 3
    position: Creative Director
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: google-plus
    #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tecvity
  - title: instagram
    url: https://instagram.com/tecvity
  - title: linkedin
    url: https://www.linkedin.com/company/80539034
  - title: github
    url: http://github.com/tecvity

# Postal address (add as many lines as necessary)
address:
  - line: Madina Colony
  - line: Gujranwala, Pakistan 52250

# Build settings
markdown: kramdown
permalink: pretty
