#url: https://y7kim.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Tecvity
email: hello@tecvity.co
description: "A one stop solution for all your software needs. We offer services in web and mobile app design and development. Find out more on our website."

# Team names, titles and social links
people:
  - name: Najam Ul Saqib
    pic: najam
    position: Chief Executive Officer (CEO)
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: stack-overflow
    #     url: #

  - name: Moeez Ahmed
    position: Chief Technological Officer (CTO)
    pic: profile-placeholder
    # social:
    #   - title: twitter
    #     url: #
    #   - title: facebook
    #     url: #
    #   - title: linkedin
    #     url: #

  - name: Tayyab Ahmed
    pic: tayyab
    position: Creative Director
    social:
      - title: linkedin
        url: https://linkedin.com/in/tayyub-ahmed

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/tecvity
  - title: instagram
    url: https://instagram.com/tecvity
  - title: linkedin
    url: https://www.linkedin.com/company/tecvity
  - title: github
    url: http://github.com/tecvity

# Postal address (add as many lines as necessary)
address:
  - line: Madina Colony
  - line: Gujranwala, Pakistan 52250

# Build settings
markdown: kramdown
permalink: pretty
